version: '3.9'

services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    volumes:
      - /home/vboxuser/ngrok.yml:/etc/ngrok.yml  # Update path
    command: start --config /etc/ngrok.yml --all
    ports:
      - "4040:4040"  # Ngrok Web Interface for monitoring
    deploy:
      placement:
        constraints:
          - node.hostname == swm-node-1 # Update node
